version: '3.9'

########################### NETWORKS
networks:
  web:
    name: web
    driver: bridge
    external: false
    attachable: true
  database:
    name: database
    driver: bridge
    external: false
    attachable: true

########################### SERVICES
services:
########################### API
  copea-newsletter-api:
    build:
      context: ./
      dockerfile: Dockerfile.build
    image: copea-newsletter-api:${BUILD_NUMBER}
    container_name: copea-newsletter-api
    environment:      
      - DB_JDBC_URL=${DB_JDBC_URL:-jdbc:postgresql://postgresql:5432/copea-newsletter}
      - DB_JDBC_USER=${DB_JDBC_USER:-postgres}
      - DB_JDBC_PASSWORD=${DB_JDBC_PASSWORD:-admin}
      - PORT=${PORT_API:-8620}
      - TZ=${TZ_API:-America/Sao_Paulo}
    ports:
      - "8620:8620"  # the HTTP endpoint
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copea-newsletter-api.rule=Host(`copea-newsletter-api.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.copea-newsletter-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.copea-newsletter-api.entrypoints=websecure"
      - "traefik.http.services.copea-newsletter-api.loadbalancer.server.port=8620"
    restart: unless-stopped
    networks:
      - web
      - database
