version: "3.8"

services:
  newsletter-db:
    image: "postgres:latest"
    container_name: newsletter-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-newsletter}
      - TZ=${TZ_DB:-America/Sao_Paulo}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5433:5432"
    networks:
      - newsletter-net

  newsletter-api:
    build:
      context: ./
      dockerfile: Dockerfile.build
    image: quarkus/newsletter
    container_name: newsletter-api
    environment:      
      - DB_JDBC_URL=${DB_JDBC_URL:-jdbc:postgresql://newsletter-db:5432/newsletter?ApplicationName=newsletter}
      - DB_JDBC_USER=${DB_JDBC_USER:-postgres}
      - DB_JDBC_PASSWORD=${DB_JDBC_PASSWORD:-admin}
      - PORT=${PORT_API:-8081}
      - TZ=${TZ_API:-America/Sao_Paulo}
    ports:
      - "8081:8081"  # the HTTP endpoint
    depends_on:
      newsletter-db:
        condition: service_healthy
    networks:
      - newsletter-net    

networks:
  newsletter-net:
    driver: bridge
